# Generated by Django 4.1.1 on 2022-09-24 17:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('ТН', 'Танки'), ('ХЛ', 'Хилы'), ('ДД', 'ДД'), ('ТГ', 'Торговцы'), ('ГМ', 'Гилдмастеры'), ('КГ', 'Квестгиверы'), ('КЗ', 'Кузнецы'), ('КЖ', 'Кожевники'), ('ЗВ', 'Зельевары'), ('МЗ', 'Мастера заклинаний')], default='Тн', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
            ],
        ),
    ]
